### ISSUE TITLE
Gravitybox system framework not responding. Exiting

### ISSUE THREAD

**Issue by droidzone** [GravityBox/GravityBox#1002]
Gravitybox fails to start with the message: "Gravitybox system framework not responding. Exiting".

Device: Nexus 2012 Wifi only 
ROM: Stock rooted Android 4.4.4
xposed is installed on internal memory. Other mods seem to work. I have tested it with all other xposed mods disabled. Same effect.

Logs: error.log

```
-----------------
Aug 9, 2014 3:09:54 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'google/nakasi/grouper:4.4.4/KTU84P/1227136:user/release-keys'
Loading modules from /data/app/com.android.xposed.finaly.bluetoothunlock-1.apk
  Loading class com.android.xposed.finaly.bluetoothunlock.BluHook
```

Full logs: error.log.old http://pastebin.com/EPaECKEa

```
-----------------
Aug 9, 2014 2:27:01 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'google/nakasi/grouper:4.4.4/KTU84P/1227136:user/release-keys'
Loading modules from /data/app/com.android.xposed.finaly.bluetoothunlock-1.apk
  Loading class com.android.xposed.finaly.bluetoothunlock.BluHook
Loading modules from /data/app/com.ceco.gm2.gravitybox-1.apk
  Loading class com.ceco.gm2.gravitybox.GravityBox
GB:Hardware: grouper
GB:Product: nakasi
GB:Device manufacturer: asus
GB:Device brand: google
GB:Device model: Nexus 7
GB:Device type: tablet
GB:Is MTK device: false
GB:Is Xperia device: false
GB:Has Lenovo custom UI: false
GB:Has telephony support: false
GB:Has Gemini support: false
GB:Android SDK: 19
GB:Android Release: 4.4.4
GB:ROM: KTU84P
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
    at com.ceco.gm2.gravitybox.ModLockscreen.initZygote(ModLockscreen.java:156)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:84)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/keyguard/KeyguardViewManager
    ... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.keyguard.KeyguardViewManager" on path: DexPathList[[zip file "/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    ... 10 more
java.lang.NoSuchMethodError: com.android.internal.policy.impl.PhoneWindowManager#getSystemDecorRectLw(android.graphics.Rect)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModStatusbarColor.initZygote(ModStatusbarColor.java:168)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:96)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NoSuchFieldError: java.util.zip.ZipFile$RAFStream#mLength
    at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
    at com.ceco.gm2.gravitybox.PatchMasterKey.<clinit>(PatchMasterKey.java:116)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:102)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at com.ceco.gm2.gravitybox.ModDisplay$6.beforeHookedMethod(ModDisplay.java:313)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.LightsService$Light.setLightLocked(Native Method)
    at com.android.server.LightsService$Light.setColor(LightsService.java:80)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.LightsService$Light.setColor(Native Method)
    at com.android.server.BatteryService$Led.updateLightsLocked(BatteryService.java:736)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.BatteryService$Led.updateLightsLocked(Native Method)
    at com.android.server.BatteryService.processValuesLocked(BatteryService.java:450)
    at com.android.server.BatteryService.update(BatteryService.java:286)
    at com.android.server.BatteryService.access$600(BatteryService.java:83)
    at com.android.server.BatteryService$BatteryListener.batteryPropertiesChanged(BatteryService.java:747)
    at android.os.IBatteryPropertiesListener$Stub.onTransact(IBatteryPropertiesListener.java:58)
    at android.os.Binder.execTransact(Binder.java:404)
    at dalvik.system.NativeStart.run(Native Method)
java.lang.NoSuchMethodError: android.media.AudioService#adjustMasterVolume(int,int)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModAudio$2.afterHookedMethod(ModAudio.java:92)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at android.media.AudioService.<init>(Native Method)
    at com.android.server.ServerThread.initAndLoop(SystemServer.java:639)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1179)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
-----------------
Aug 9, 2014 2:31:17 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'google/nakasi/grouper:4.4.4/KTU84P/1227136:user/release-keys'
Loading modules from /data/app/com.android.xposed.finaly.bluetoothunlock-1.apk
  Loading class com.android.xposed.finaly.bluetoothunlock.BluHook
Loading modules from /data/app/com.ceco.gm2.gravitybox-1.apk
  Loading class com.ceco.gm2.gravitybox.GravityBox
GB:Hardware: grouper
GB:Product: nakasi
GB:Device manufacturer: asus
GB:Device brand: google
GB:Device model: Nexus 7
GB:Device type: tablet
GB:Is MTK device: false
GB:Is Xperia device: false
GB:Has Lenovo custom UI: false
GB:Has telephony support: false
GB:Has Gemini support: false
GB:Android SDK: 19
GB:Android Release: 4.4.4
GB:ROM: KTU84P
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
    at com.ceco.gm2.gravitybox.ModLockscreen.initZygote(ModLockscreen.java:156)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:84)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/keyguard/KeyguardViewManager
    ... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.keyguard.KeyguardViewManager" on path: DexPathList[[zip file "/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    ... 10 more
java.lang.NoSuchMethodError: com.android.internal.policy.impl.PhoneWindowManager#getSystemDecorRectLw(android.graphics.Rect)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModStatusbarColor.initZygote(ModStatusbarColor.java:168)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:96)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NoSuchFieldError: java.util.zip.ZipFile$RAFStream#mLength
    at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
    at com.ceco.gm2.gravitybox.PatchMasterKey.<clinit>(PatchMasterKey.java:116)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:102)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at com.ceco.gm2.gravitybox.ModDisplay$6.beforeHookedMethod(ModDisplay.java:313)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.LightsService$Light.setLightLocked(Native Method)
    at com.android.server.LightsService$Light.setColor(LightsService.java:80)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.LightsService$Light.setColor(Native Method)
    at com.android.server.BatteryService$Led.updateLightsLocked(BatteryService.java:736)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.BatteryService$Led.updateLightsLocked(Native Method)
    at com.android.server.BatteryService.processValuesLocked(BatteryService.java:450)
    at com.android.server.BatteryService.update(BatteryService.java:286)
    at com.android.server.BatteryService.access$600(BatteryService.java:83)
    at com.android.server.BatteryService$BatteryListener.batteryPropertiesChanged(BatteryService.java:747)
    at android.os.IBatteryPropertiesListener$Stub.onTransact(IBatteryPropertiesListener.java:58)
    at android.os.Binder.execTransact(Binder.java:404)
    at dalvik.system.NativeStart.run(Native Method)
java.lang.NoSuchMethodError: android.media.AudioService#adjustMasterVolume(int,int)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModAudio$2.afterHookedMethod(ModAudio.java:92)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at android.media.AudioService.<init>(Native Method)
    at com.android.server.ServerThread.initAndLoop(SystemServer.java:639)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1179)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
-----------------
Aug 9, 2014 2:39:08 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'google/nakasi/grouper:4.4.4/KTU84P/1227136:user/release-keys'
Loading modules from /data/app/com.android.xposed.finaly.bluetoothunlock-1.apk
  Loading class com.android.xposed.finaly.bluetoothunlock.BluHook
Loading modules from /data/app/com.ceco.gm2.gravitybox-1.apk
  Loading class com.ceco.gm2.gravitybox.GravityBox
GB:Hardware: grouper
GB:Product: nakasi
GB:Device manufacturer: asus
GB:Device brand: google
GB:Device model: Nexus 7
GB:Device type: tablet
GB:Is MTK device: false
GB:Is Xperia device: false
GB:Has Lenovo custom UI: false
GB:Has telephony support: false
GB:Has Gemini support: false
GB:Android SDK: 19
GB:Android Release: 4.4.4
GB:ROM: KTU84P
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
    at com.ceco.gm2.gravitybox.ModLockscreen.initZygote(ModLockscreen.java:156)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:84)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/keyguard/KeyguardViewManager
    ... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.keyguard.KeyguardViewManager" on path: DexPathList[[zip file "/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    ... 10 more
java.lang.NoSuchMethodError: com.android.internal.policy.impl.PhoneWindowManager#getSystemDecorRectLw(android.graphics.Rect)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModStatusbarColor.initZygote(ModStatusbarColor.java:168)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:96)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NoSuchFieldError: java.util.zip.ZipFile$RAFStream#mLength
    at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
    at com.ceco.gm2.gravitybox.PatchMasterKey.<clinit>(PatchMasterKey.java:116)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:102)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at com.ceco.gm2.gravitybox.ModDisplay$6.beforeHookedMethod(ModDisplay.java:313)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.LightsService$Light.setLightLocked(Native Method)
    at com.android.server.LightsService$Light.setColor(LightsService.java:80)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.LightsService$Light.setColor(Native Method)
    at com.android.server.BatteryService$Led.updateLightsLocked(BatteryService.java:736)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.BatteryService$Led.updateLightsLocked(Native Method)
    at com.android.server.BatteryService.processValuesLocked(BatteryService.java:450)
    at com.android.server.BatteryService.update(BatteryService.java:286)
    at com.android.server.BatteryService.access$600(BatteryService.java:83)
    at com.android.server.BatteryService$BatteryListener.batteryPropertiesChanged(BatteryService.java:747)
    at android.os.IBatteryPropertiesListener$Stub.onTransact(IBatteryPropertiesListener.java:58)
    at android.os.Binder.execTransact(Binder.java:404)
    at dalvik.system.NativeStart.run(Native Method)
java.lang.NoSuchMethodError: android.media.AudioService#adjustMasterVolume(int,int)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModAudio$2.afterHookedMethod(ModAudio.java:92)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at android.media.AudioService.<init>(Native Method)
    at com.android.server.ServerThread.initAndLoop(SystemServer.java:639)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1179)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
-----------------
Aug 9, 2014 3:05:58 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'google/nakasi/grouper:4.4.4/KTU84P/1227136:user/release-keys'
Loading modules from /data/app/com.android.xposed.finaly.bluetoothunlock-1.apk
  Loading class com.android.xposed.finaly.bluetoothunlock.BluHook
Loading modules from /data/app/com.ceco.gm2.gravitybox-1.apk
  Loading class com.ceco.gm2.gravitybox.GravityBox
GB:Hardware: grouper
GB:Product: nakasi
GB:Device manufacturer: asus
GB:Device brand: google
GB:Device model: Nexus 7
GB:Device type: tablet
GB:Is MTK device: false
GB:Is Xperia device: false
GB:Has Lenovo custom UI: false
GB:Has telephony support: false
GB:Has Gemini support: false
GB:Android SDK: 19
GB:Android Release: 4.4.4
GB:ROM: KTU84P
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
    at com.ceco.gm2.gravitybox.ModLockscreen.initZygote(ModLockscreen.java:156)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:84)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.impl.keyguard.KeyguardViewManager
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
    at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: com/android/internal/policy/impl/keyguard/KeyguardViewManager
    ... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.impl.keyguard.KeyguardViewManager" on path: DexPathList[[zip file "/data/data/de.robv.android.xposed.installer/bin/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    ... 10 more
java.lang.NoSuchMethodError: com.android.internal.policy.impl.PhoneWindowManager#getSystemDecorRectLw(android.graphics.Rect)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModStatusbarColor.initZygote(ModStatusbarColor.java:168)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:96)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NoSuchFieldError: java.util.zip.ZipFile$RAFStream#mLength
    at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
    at com.ceco.gm2.gravitybox.PatchMasterKey.<clinit>(PatchMasterKey.java:116)
    at com.ceco.gm2.gravitybox.GravityBox.initZygote(GravityBox.java:102)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:437)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at com.ceco.gm2.gravitybox.ModDisplay$6.beforeHookedMethod(ModDisplay.java:313)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.LightsService$Light.setLightLocked(Native Method)
    at com.android.server.LightsService$Light.setColor(LightsService.java:80)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.LightsService$Light.setColor(Native Method)
    at com.android.server.BatteryService$Led.updateLightsLocked(BatteryService.java:736)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.BatteryService$Led.updateLightsLocked(Native Method)
    at com.android.server.BatteryService.processValuesLocked(BatteryService.java:450)
    at com.android.server.BatteryService.update(BatteryService.java:286)
    at com.android.server.BatteryService.access$600(BatteryService.java:83)
    at com.android.server.BatteryService$BatteryListener.batteryPropertiesChanged(BatteryService.java:747)
    at android.os.IBatteryPropertiesListener$Stub.onTransact(IBatteryPropertiesListener.java:58)
    at android.os.Binder.execTransact(Binder.java:404)
    at dalvik.system.NativeStart.run(Native Method)
java.lang.NoSuchMethodError: android.media.AudioService#adjustMasterVolume(int,int)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at com.ceco.gm2.gravitybox.ModAudio$2.afterHookedMethod(ModAudio.java:92)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at android.media.AudioService.<init>(Native Method)
    at com.android.server.ServerThread.initAndLoop(SystemServer.java:639)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1179)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by C3C0** [comment]
You installed JellyBean version of GravityBox on KitKat. I wonder how that's even possible since apk has SDK version restriction and refuses to install on anything lower than KitKat. Make sure to remove any traces of GB apk you currently have on your device and install the correct version from here: http://repo.xposed.info/module/com.ceco.kitkat.gravitybox
