### ISSUE TITLE
To much log messages on AOSP LP

### ISSUE THREAD

**Issue by mittorn** [GravityBox/GravityBox#1380]
```
8-29 07:32:54.182 E/Xposed  (  841): java.lang.NoSuchMethodError: com.mediatek.systemui.ext.DefaultStatusBarPlugin#getDataNetworkTypeIconGemini(com.mediatek.systemui.ext.NetworkType,int)#exact
08-29 07:32:54.182 E/Xposed  (  841):   at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:170)
08-29 07:32:54.182 E/Xposed  (  841):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:131)
08-29 07:32:54.182 E/Xposed  (  841):   at com.ceco.lollipop.gravitybox.ModStatusBar$28.afterHookedMethod(ModStatusBar.java:1141)
08-29 07:32:54.182 E/Xposed  (  841):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)
08-29 07:32:54.182 E/Xposed  (  841):   at com.mediatek.systemui.ext.PluginFactory.getStatusBarPlugin(<Xposed>)
08-29 07:32:54.182 E/Xposed  (  841):   at com.android.systemui.statusbar.SignalClusterView.apply(SignalClusterView.java:401)
08-29 07:32:54.182 E/Xposed  (  841):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshViews(NetworkControllerImpl.java:1986)
08-29 07:32:54.182 E/Xposed  (  841):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshViews(NetworkControllerImpl.java:1679)
08-29 07:32:54.182 E/Xposed  (  841):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.onReceive(NetworkControllerImpl.java:643)
08-29 07:32:54.182 E/Xposed  (  841):   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:895)
08-29 07:32:54.182 E/Xposed  (  841):   at android.os.Handler.handleCallback(Handler.java:810)
08-29 07:32:54.182 E/Xposed  (  841):   at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 07:32:54.182 E/Xposed  (  841):   at android.os.Looper.loop(Looper.java:189)
08-29 07:32:54.182 E/Xposed  (  841):   at android.app.ActivityThread.main(ActivityThread.java:5529)
08-29 07:32:54.182 E/Xposed  (  841):   at java.lang.reflect.Method.invoke(Native Method)
08-29 07:32:54.182 E/Xposed  (  841):   at java.lang.reflect.Method.invoke(Method.java:372)
08-29 07:32:54.182 E/Xposed  (  841):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
```

**Comment by mittorn** [comment]
This repeats on every network status update

**Comment by mittorn** [comment]
It seems, that it is already fixed in
https://github.com/GravityBox/GravityBox/commit/725b677baa018aede0dc255788ad96f73921f636
But it was not fixed in latest LP release.
Note that my device has big "3G" icon near to network status, but hiding icon does not work. Unchecking it does not shut up this exceptions too

**Comment by C3C0** [comment]
Version with the fix was not released yet.

**Comment by mittorn** [comment]
Can you release it as hotfix?
It's very difficult to read logs without filtering, but somtimes i need not filtered log.

**Comment by C3C0** [comment]
http://forum.xda-developers.com/showpost.php?p=62594197&postcount=2747
