### ISSUE TITLE
[MM] Now on Tap with Pie not working

### ISSUE THREAD

**Issue by wardellbagby** [GravityBox/GravityBox#1445]
Every time I try to use the Now on Tap (Pie home button long press set to Search), System UI crashes. This only happens if I have disabled the navigation bar and am using Pie Controls to trigger it.

I'm using a Nexus 6P on stock 6.0.1. 

Now on Tap works correctly when using the on-screen navigation keys.

I was able to get a stack trace and I believe is the trace of the crash:

Process: com.android.systemui, PID: 19713
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.systemui.assist.AssistOrbView com.android.systemui.assist.AssistOrbContainer.getOrb()' on a null object reference
            at com.android.systemui.assist.AssistManager.maybeSwapSearchIcon(AssistManager.java:248)
            at com.android.systemui.assist.AssistManager.showOrb(AssistManager.java:165)
            at com.android.systemui.assist.AssistManager.startAssist(AssistManager.java:133)
            at com.android.systemui.statusbar.BaseStatusBar.startAssist(BaseStatusBar.java:2215)
            at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:402)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

Let me know if there's any more information I can provide.

**Comment by wardellbagby** [comment]
If I set the Navigation Bar height and width to 0, Now on Tap seems to work fine with Search.
