### ISSUE TITLE
The amPmIndex might be wrongly calculated without consideration of different AM/PM positions.

### ISSUE THREAD

**Issue by Goshin** [GravityBox/GravityBox#1451]
In the `StatusbarClock.java`, line 177 :

``` java
if (amPmIndex > -1) {
    int offset = Character.isWhitespace(clockText.charAt(dow.length() + date.length() + amPmIndex - 1)) ?
            1 : 0;
    sb.setSpan(new RelativeSizeSpan(mAmPmSize), dow.length() + date.length() + amPmIndex - offset, 
            dow.length() + date.length() + amPmIndex + amPm.length(), 
            Spannable.SPAN_EXCLUSIVE_INCLUSIVE);
}
```

The AM/PM text seems to be considered placed in the end of the clock text.
However, in some devices, the AM/PM is treated as the first part in the clock text, resulting the wrongly processing in the program above. In some cases, it could cause an exception as below:

```
java.lang.StringIndexOutOfBoundsException: length=7; index=-1
    at java.lang.String.indexAndLength(String.java:584)
    at java.lang.String.charAt(String.java:578)
    at com.ceco.kitkat.gravitybox.StatusbarClock$1.afterHookedMethod(StatusbarClock.java:183)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at com.android.systemui.statusbar.policy.Clock.getSmallTime(Native Method)
    at com.android.systemui.statusbar.policy.Clock.updateClock(Clock.java:135)
    at com.android.systemui.statusbar.policy.Clock$1.onReceive(Clock.java:128)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5323)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

In this case, the `day of week` and `date` options are disabled, and the clock text begins with the AM/PM, like `下午03:00`

My simple patch for Kitkat: https://github.com/Goshin/GravityBox/commit/122a06ed3e80475e1ceb41aff08098ba816489f5?diff=unified

**Comment by C3C0** [comment]
Interesting. Which devices and language do you mean? I tried different languages on my device and all of them have am/pm to the right of the clock.

**Comment by Goshin** [comment]
I tried Chinese and English in my tablet (Kitkat).

The screenshots:

![screenshot2](https://cloud.githubusercontent.com/assets/10056397/12409159/805e82d8-bea2-11e5-8c29-189ae1fa2390.png)

![screenshot1](https://cloud.githubusercontent.com/assets/10056397/12409148/6c93f4f4-bea2-11e5-8d3b-ecdfd90aab3a.png)

**Comment by Goshin** [comment]
So, what do you think?

**Comment by C3C0** [comment]
I just merged one commit from Lollipop branch posted by other user some time ago, which explicitly places AM/PM in front of clock for Chinese locales. Please, check if additional adjustments are required. If yes, feel free to send a pull request.
https://github.com/GravityBox/GravityBox/commit/521ca63be3d44f9e26569d188636e2a9a0730aff

**Comment by Goshin** [comment]
Great, the problem was solved nicely.
Feel free to close this issue.
