### ISSUE TITLE
Xposed log - Errors

### ISSUE THREAD

**Issue by lenisko** [GravityBox/GravityBox#1475]
A loot of errors, maybe worth posting there.
Device: Lenovo TAB 2 A10-70L (LENOVO), Android version 5.0.1 (SDK 21)
Installed modules on device https://i.imgur.com/gT4N8OZ.png

```
02-29 02:32:50.788 I/Xposed  (  250): -----------------
02-29 02:32:50.788 I/Xposed  (  250): Starting Xposed version 80, compiled for SDK 21
02-29 02:32:50.788 I/Xposed  (  250): Device: Lenovo TAB 2 A10-70L (LENOVO), Android version 5.0.1 (SDK 21)
02-29 02:32:50.788 I/Xposed  (  250): ROM: A10-70L_S000116_160129_ROW
02-29 02:32:50.788 I/Xposed  (  250): Build fingerprint: Lenovo/LenovoTAB2A10-70L/A10-70L:5.0.1/LRX21M/A10-70L_S000116_160129_ROW:user/release-keys
02-29 02:32:50.788 I/Xposed  (  250): Platform: arm64-v8a, 64-bit binary, system server: yes
02-29 02:32:50.788 I/Xposed  (  250): SELinux enabled: yes, enforcing: yes
02-29 02:32:50.801 I/Xposed  (  250): -----------------
02-29 02:32:50.801 I/Xposed  (  250): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-29 02:32:51.088 I/Xposed  (  250): Detected ART runtime
02-29 02:32:51.110 I/Xposed  (  250): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
02-29 02:32:51.469 I/Xposed  (  250): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LACK-2/base.apk
02-29 02:32:51.741 I/Xposed  (  250):   Loading class com.chelpus.XSupport
02-29 02:32:51.804 I/Xposed  (  250): Loading modules from /data/app/it.matsca09.xposedmod.directapkinstall-1/base.apk
02-29 02:32:51.825 I/Xposed  (  250):   Loading class it.matsca09.xposedmod.directapkinstall.DirectInstallMod
02-29 02:32:51.863 I/Xposed  (  250): Loading modules from /data/app/com.anton111111.xposed.multiusers-1/base.apk
02-29 02:32:51.909 I/Xposed  (  250):   Loading class com.anton111111.xposed.multiusers.Main
02-29 02:32:51.925 I/Xposed  (  250): Loading modules from /data/app/com.ceco.lollipop.gravitybox-1/base.apk
02-29 02:32:52.042 I/Xposed  (  250):   Loading class com.ceco.lollipop.gravitybox.GravityBox
02-29 02:32:52.075 I/Xposed  (  250): GB:Hardware: mt6752
02-29 02:32:52.075 I/Xposed  (  250): GB:Product: LenovoTAB2A10-70L
02-29 02:32:52.075 I/Xposed  (  250): GB:Device manufacturer: LENOVO
02-29 02:32:52.075 I/Xposed  (  250): GB:Device brand: Lenovo
02-29 02:32:52.076 I/Xposed  (  250): GB:Device model: Lenovo TAB 2 A10-70L
02-29 02:32:52.081 I/Xposed  (  250): GB:Device type: tablet
02-29 02:32:52.081 I/Xposed  (  250): GB:Is MTK device: true
02-29 02:32:52.081 I/Xposed  (  250): GB:Is Xperia device: false
02-29 02:32:52.081 I/Xposed  (  250): GB:Is Moto XT device: false
02-29 02:32:52.082 I/Xposed  (  250): GB:Has Lenovo custom UI: false
02-29 02:32:52.083 I/Xposed  (  250): GB:Has telephony support: false
02-29 02:32:52.086 I/Xposed  (  250): GB:Has Gemini support: false
02-29 02:32:52.086 I/Xposed  (  250): GB:Android SDK: 21
02-29 02:32:52.086 I/Xposed  (  250): GB:Android Release: 5.0.1
02-29 02:32:52.086 I/Xposed  (  250): GB:ROM: A10-70L_S000116_160129_ROW
02-29 02:33:00.417 I/Xposed  (  251): -----------------
02-29 02:33:00.417 I/Xposed  (  251): Starting Xposed version 80, compiled for SDK 21
02-29 02:33:00.417 I/Xposed  (  251): Device: Lenovo TAB 2 A10-70L (LENOVO), Android version 5.0.1 (SDK 21)
02-29 02:33:00.417 I/Xposed  (  251): ROM: A10-70L_S000116_160129_ROW
02-29 02:33:00.417 I/Xposed  (  251): Build fingerprint: Lenovo/LenovoTAB2A10-70L/A10-70L:5.0.1/LRX21M/A10-70L_S000116_160129_ROW:user/release-keys
02-29 02:33:00.417 I/Xposed  (  251): Platform: arm64-v8a, 32-bit binary, system server: no
02-29 02:33:00.417 I/Xposed  (  251): SELinux enabled: yes, enforcing: yes
02-29 02:33:00.424 I/Xposed  (  251): -----------------
02-29 02:33:00.424 I/Xposed  (  251): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-29 02:33:00.716 I/Xposed  (  251): Detected ART runtime
02-29 02:33:00.740 I/Xposed  (  251): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
02-29 02:33:01.076 I/Xposed  (  251): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LACK-2/base.apk
02-29 02:33:01.325 I/Xposed  (  251):   Loading class com.chelpus.XSupport
02-29 02:33:01.367 I/Xposed  (  251): Loading modules from /data/app/it.matsca09.xposedmod.directapkinstall-1/base.apk
02-29 02:33:01.384 I/Xposed  (  251):   Loading class it.matsca09.xposedmod.directapkinstall.DirectInstallMod
02-29 02:33:01.392 I/Xposed  (  251): Loading modules from /data/app/com.anton111111.xposed.multiusers-1/base.apk
02-29 02:33:01.432 I/Xposed  (  251):   Loading class com.anton111111.xposed.multiusers.Main
02-29 02:33:01.450 I/Xposed  (  251): Loading modules from /data/app/com.ceco.lollipop.gravitybox-1/base.apk
02-29 02:33:01.564 I/Xposed  (  251):   Loading class com.ceco.lollipop.gravitybox.GravityBox
02-29 02:33:24.728 I/Xposed  (  698): getMaxSupportedUsers return value: 4
02-29 02:33:24.728 I/Xposed  (  698): supportsMultipleUsers return value: false
02-29 02:33:24.728 I/Xposed  (  698): Override result of supportsMultipleUsers to true
02-29 02:33:26.674 E/Xposed  ( 1055): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.keyguard.CarrierText
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:55)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
02-29 02:33:26.674 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.ModLockscreen.init(ModLockscreen.java:457)
02-29 02:33:26.674 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:195)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:35)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:71)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:176)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:661)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.app.ActivityThread.access$1500(ActivityThread.java:167)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.os.Handler.dispatchMessage(Handler.java:111)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.os.Looper.loop(Looper.java:194)
02-29 02:33:26.674 E/Xposed  ( 1055):   at android.app.ActivityThread.main(ActivityThread.java:5534)
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.reflect.Method.invoke(Native Method)
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.reflect.Method.invoke(Method.java:372)
02-29 02:33:26.674 E/Xposed  ( 1055):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
02-29 02:33:26.674 E/Xposed  ( 1055):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
02-29 02:33:26.674 E/Xposed  ( 1055): Caused by: java.lang.ClassNotFoundException: com.android.keyguard.CarrierText
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.Class.classForName(Native Method)
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.Class.forName(Class.java:308)
02-29 02:33:26.674 E/Xposed  ( 1055):   at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
02-29 02:33:26.674 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:53)
02-29 02:33:26.674 E/Xposed  ( 1055):   ... 19 more
02-29 02:33:26.674 E/Xposed  ( 1055): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.keyguard.CarrierText" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
02-29 02:33:26.674 E/Xposed  ( 1055):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-29 02:33:26.674 E/Xposed  ( 1055):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-29 02:33:26.674 E/Xposed  ( 1055):   ... 23 more
02-29 02:33:26.674 E/Xposed  ( 1055):   Suppressed: java.lang.ClassNotFoundException: com.android.keyguard.CarrierText
02-29 02:33:26.674 E/Xposed  ( 1055):       at java.lang.Class.classForName(Native Method)
02-29 02:33:26.674 E/Xposed  ( 1055):       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-29 02:33:26.674 E/Xposed  ( 1055):       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-29 02:33:26.674 E/Xposed  ( 1055):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-29 02:33:26.674 E/Xposed  ( 1055):       ... 24 more
02-29 02:33:26.674 E/Xposed  ( 1055):   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
02-29 02:33:29.356 I/Xposed  ( 1055): getMaxSupportedUsers return value: 4
02-29 02:33:29.479 I/Xposed  ( 1055): getMaxSupportedUsers return value: 4
02-29 02:33:29.515 E/Xposed  ( 1055): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.mediatek.systemui.qs.tiles.MobileDataTile
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:55)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.quicksettings.AospTile.createHooks(AospTile.java:93)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.quicksettings.AospTile.<init>(AospTile.java:59)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.quicksettings.MtkMobileDataTile.<init>(MtkMobileDataTile.java:24)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.quicksettings.AospTile.create(AospTile.java:45)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.ceco.lollipop.gravitybox.ModQsTiles$1.afterHookedMethod(ModQsTiles.java:120)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:695)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.QSTileHost.recreateTiles(<Xposed>)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.QSTileHost.<init>(QSTileHost.java:177)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.SetQSTiles(PhoneStatusBar.java:4514)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:972)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(<Xposed>)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3108)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3104)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:512)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.BaseStatusBar.start(<Xposed>)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:621)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
02-29 02:33:29.515 E/Xposed  ( 1055):   at android.os.Handler.dispatchMessage(Handler.java:111)
02-29 02:33:29.515 E/Xposed  ( 1055):   at android.os.Looper.loop(Looper.java:194)
02-29 02:33:29.515 E/Xposed  ( 1055):   at android.app.ActivityThread.main(ActivityThread.java:5534)
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.reflect.Method.invoke(Native Method)
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.reflect.Method.invoke(Method.java:372)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
02-29 02:33:29.515 E/Xposed  ( 1055):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
02-29 02:33:29.515 E/Xposed  ( 1055): Caused by: java.lang.ClassNotFoundException: com.mediatek.systemui.qs.tiles.MobileDataTile
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.Class.classForName(Native Method)
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.Class.forName(Class.java:308)
02-29 02:33:29.515 E/Xposed  ( 1055):   at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
02-29 02:33:29.515 E/Xposed  ( 1055):   at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:53)
02-29 02:33:29.515 E/Xposed  ( 1055):   ... 34 more
02-29 02:33:29.515 E/Xposed  ( 1055): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mediatek.systemui.qs.tiles.MobileDataTile" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
02-29 02:33:29.515 E/Xposed  ( 1055):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-29 02:33:29.515 E/Xposed  ( 1055):   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-29 02:33:29.515 E/Xposed  ( 1055):   ... 38 more
02-29 02:33:29.515 E/Xposed  ( 1055):   Suppressed: java.lang.ClassNotFoundException: com.mediatek.systemui.qs.tiles.MobileDataTile
02-29 02:33:29.515 E/Xposed  ( 1055):       at java.lang.Class.classForName(Native Method)
02-29 02:33:29.515 E/Xposed  ( 1055):       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-29 02:33:29.515 E/Xposed  ( 1055):       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-29 02:33:29.515 E/Xposed  ( 1055):       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-29 02:33:29.515 E/Xposed  ( 1055):       ... 39 more
02-29 02:33:29.515 E/Xposed  ( 1055):   Caused by: 
02-29 02:33:29.806 I/Xposed  ( 1055): GB:StatusbarBattery: Error backing up original colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:29.806 I/Xposed  ( 1055): GB:StatusbarBattery: Error setting colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:29.808 I/Xposed  ( 1055): GB:StatusbarBattery: Error backing up original colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:29.808 I/Xposed  ( 1055): GB:StatusbarBattery: Error setting colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:29.814 I/Xposed  ( 1055): GB:StatusbarBattery: Error backing up original colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:29.814 I/Xposed  ( 1055): GB:StatusbarBattery: Error setting colors: com.android.systemui.BatteryMeterView#mColors
02-29 02:33:30.743 I/Xposed  (  698): getMaxSupportedUsers return value: 4
02-29 02:33:30.743 I/Xposed  (  698): supportsMultipleUsers return value: false
02-29 02:33:30.743 I/Xposed  (  698): Override result of supportsMultipleUsers to true
```

**Comment by C3C0** [comment]
GravityBox does not officially support devices that come with system that has major changes made by device's vendor on top of pure Android. Lenovo is one of them. Similar situation as with Samsung devices running Touchwiz or HTC running Sense jut to name a few.
