### ISSUE TITLE
[bug] [MM] proximity wake-up freeze

### ISSUE THREAD

**Issue by alexbilevskiy** [GravityBox/GravityBox#1542]
xperia z3c with _sony concept firmware_ (it's android 6.0, almost pure aosp)
Sometimes phone freezes with black screen when you cover sensor, lock phone with power button and instantly try to unlock.

locgat *:W says:

```
04-25 00:47:28.989  1240  1263 W qti_sensors_hal: sendCancel:sensor(android.sensor.proximity) start sleeping 200ms
04-25 00:47:29.190  1240  1263 W qti_sensors_hal: sendCancel:sensor(android.sensor.proximity) done sleeping 200ms!
04-25 00:47:32.856  1240  1263 W qti_sensors_hal: sendCancel:sensor(android.sensor.proximity) start sleeping 200ms
04-25 00:47:33.057  1240  1263 W qti_sensors_hal: sendCancel:sensor(android.sensor.proximity) done sleeping 200ms!
04-25 00:47:35.234   327   327 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 2
04-25 00:47:50.243   327   327 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 3
04-25 00:48:10.255   327   327 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 4
04-25 00:48:35.265   327   327 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 5
04-25 00:49:02.910  1240  9156 W DropBoxManagerService: Dropping: system_server_watchdog (10 > 0 bytes)
04-25 00:49:02.911  1240  2443 W Watchdog: *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in monitor com.android.server.power.PowerManagerService on foreground thread (android.fg), Blocked in handler on main thread (main), Blocked in handler on ActivityManager (ActivityManager), Blocked in handler on PowerManagerService (PowerManagerService)
04-25 00:49:02.911  1240  2443 W Watchdog: foreground thread stack trace:
04-25 00:49:02.911  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService.monitor(PowerManagerService.java:2585)
04-25 00:49:02.911  1240  2443 W Watchdog:     at com.android.server.Watchdog$HandlerChecker.run(Watchdog.java:172)
04-25 00:49:02.911  1240  2443 W Watchdog:     at android.os.Handler.handleCallback(Handler.java:739)
04-25 00:49:02.911  1240  2443 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-25 00:49:02.912  1240  2443 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
04-25 00:49:02.912  1240  2443 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-25 00:49:02.912  1240  2443 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-25 00:49:02.912  1240  2443 W Watchdog: main thread stack trace:
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService.wakeUpInternal(PowerManagerService.java:1059)
04-25 00:49:02.913  1240  2443 W Watchdog:     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-25 00:49:02.913  1240  2443 W Watchdog:     at de.robv.android.xposed.XposedBridge.invokeOriginalMethod(XposedBridge.java:794)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.ceco.marshmallow.gravitybox.ModPower$4$1.run(ModPower.java:119)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.ceco.marshmallow.gravitybox.ModPower$2.onSensorChanged(ModPower.java:228)
04-25 00:49:02.913  1240  2443 W Watchdog:     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:481)
04-25 00:49:02.913  1240  2443 W Watchdog:     at android.os.MessageQueue.nativePollOnce(Native Method)
04-25 00:49:02.913  1240  2443 W Watchdog:     at android.os.MessageQueue.next(MessageQueue.java:323)
04-25 00:49:02.913  1240  2443 W Watchdog:     at android.os.Looper.loop(Looper.java:135)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.server.SystemServer.run(SystemServer.java:288)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.server.SystemServer.main(SystemServer.java:173)
04-25 00:49:02.913  1240  2443 W Watchdog:     at java.lang.reflect.Method.invoke(Native Method)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 00:49:02.913  1240  2443 W Watchdog:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
04-25 00:49:02.913  1240  2443 W Watchdog: ActivityManager stack trace:
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.server.DeviceIdleController.addPowerSaveTempWhitelistAppDirectInternal(DeviceIdleController.java:1077)
04-25 00:49:02.913  1240  2443 W Watchdog:     at com.android.server.DeviceIdleController$LocalService.addPowerSaveTempWhitelistAppDirect(DeviceIdleController.java:807)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:178)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-25 00:49:02.914  1240  2443 W Watchdog: PowerManagerService stack trace:
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService.releaseWakeLockInternal(PowerManagerService.java:850)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService.-wrap23(PowerManagerService.java)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService$BinderService.releaseWakeLock(PowerManagerService.java:3064)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.PowerManager$WakeLock.release(PowerManager.java:1150)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.PowerManager$WakeLock.release(PowerManager.java:1128)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.ceco.marshmallow.gravitybox.ModPower.unregisterProxSensorListener(ModPower.java:210)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.ceco.marshmallow.gravitybox.ModPower.access$16(ModPower.java:204)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.ceco.marshmallow.gravitybox.ModPower$5.beforeHookedMethod(ModPower.java:141)
04-25 00:49:02.914  1240  2443 W Watchdog:     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.power.PowerManagerService$PowerManagerHandler.handleMessage(<Xposed>)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
04-25 00:49:02.914  1240  2443 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-25 00:49:02.914  1240  2443 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-25 00:49:02.914  1240  2443 W Watchdog: *** GOODBYE!
04-25 00:49:03.003  5126  5146 W Sensors : sensorservice died [0xb3a53900]
04-25 00:49:03.003  3250  6270 W Sensors : sensorservice died [0xa72825c0]
04-25 00:49:03.006  2017  2641 W Sensors : sensorservice died [0x9dc6e2c0]
04-25 00:49:03.011  2493  2588 W Sensors : sensorservice died [0xa7282500]
04-25 00:49:03.011   304  1971 W Sensors : sensorservice died [0xae7fe700]
04-25 00:49:03.011   304  1971 W AudioFlinger: power manager service died !!!
04-25 00:49:03.011   304  1971 W AudioFlinger: power manager service died !!!
04-25 00:49:03.011   304  1971 W AudioFlinger: power manager service died !!!
04-25 00:49:03.022  3250  3398 E WifiManager: Channel connection lost
04-25 00:49:03.022  2017  2418 E WifiManager: Channel connection lost
04-25 00:49:03.024  2563  3028 E WifiManager: Channel connection lost
04-25 00:49:03.051  5126  6765 E WifiManager: Channel connection lost
04-25 00:49:03.052  3655  3677 E WifiManager: Channel connection lost
04-25 00:49:03.057  3250  6192 W UserManager: Could not get userHandle for user 0
```

First two lines are normal lock and unlock and then phone freezes

**Comment by C3C0** [comment]
I can't reproduce such anomaly on my AOSP device which means it's something Xperia specific. Unfortunately, there is nothing I can do without being able to test on a real xperia device.
