### ISSUE TITLE
GB MM 6.3.2-rev1 crashes in quicksettings ordering Activity

### ISSUE THREAD

**Issue by Maxr1998** [GravityBox/GravityBox#1633]
**Device:** Nexus 6P
**ROM:** Android 6.0.1 MTC19X
**Reproduce:** Open TileOrderActivity => instant crash
**Stacktrace:**
```
12-27 22:49:26.873 E/AndroidRuntime(20754): FATAL EXCEPTION: main
12-27 22:49:26.873 E/AndroidRuntime(20754): Process: com.ceco.marshmallow.gravitybox, PID: 20754
12-27 22:49:26.873 E/AndroidRuntime(20754): java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.Utils.log(Utils.java:114)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.Utils.access$0(Utils.java:113)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.Utils$SystemProp.get(Utils.java:708)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.Utils.isOxygenOs35Rom(Utils.java:282)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.quicksettings.TileOrderActivity.supportedTile(TileOrderActivity.java:272)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.quicksettings.TileOrderActivity.updateDefaultTileList(TileOrderActivity.java:207)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.ceco.marshmallow.gravitybox.quicksettings.TileOrderActivity.onCreate(TileOrderActivity.java:168)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.Activity.performCreate(Activity.java:6251)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.os.Looper.loop(Looper.java:148)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at android.app.ActivityThread.main(ActivityThread.java:5422)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at java.lang.reflect.Method.invoke(Native Method)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
12-27 22:49:26.873 E/AndroidRuntime(20754): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedBridge" on path: DexPathList[[zip file "/data/app/com.ceco.marshmallow.gravitybox-2/base.apk"],nativeLibraryDirectories=[/data/app/com.ceco.marshmallow.gravitybox-2/lib/arm64, /vendor/lib64, /system/lib64]]
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-27 22:49:26.873 E/AndroidRuntime(20754): 	... 20 more
12-27 22:49:26.873 E/AndroidRuntime(20754): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedBridge" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
12-27 22:49:26.873 E/AndroidRuntime(20754): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-27 22:49:26.873 E/AndroidRuntime(20754): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
12-27 22:49:26.873 E/AndroidRuntime(20754): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
12-27 22:49:26.873 E/AndroidRuntime(20754): 		... 21 more
12-27 22:49:26.873 E/AndroidRuntime(20754): 		Suppressed: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
12-27 22:49:26.873 E/AndroidRuntime(20754): 			at java.lang.Class.classForName(Native Method)
12-27 22:49:26.873 E/AndroidRuntime(20754): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-27 22:49:26.873 E/AndroidRuntime(20754): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-27 22:49:26.873 E/AndroidRuntime(20754): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
12-27 22:49:26.873 E/AndroidRuntime(20754): 			... 22 more
12-27 22:49:26.873 E/AndroidRuntime(20754): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by gaich** [comment]
Can`t understand the technical details, but for me pressing Quick settings tiles in Statusbar settings-Quick settings menu results in GB crash and force close.
VERSION.RELEASE: 6.0
BRAND: ulefone
DEVICE: Vienna
MANUFACTURER: ulefone
MODEL: Vienna
OS.VERSION: 3.18.19
BOOTLOADER: unknown
HARDWARE: mt6735

**Comment by C3C0** [comment]
Revision2 of v6.3.2 available. Thanks for reporting.

**Comment by Maxr1998** [comment]
Thanks for the fast fix! Downloading now.
