### ISSUE TITLE
[Bug] OnePlus 6 - QuickTap launcher

### ISSUE THREAD

**Issue by W1ldKard** [GravityBox/GravityBox#1965]
OnePlus 6 - Oxygen OS 9.0.4
edXposed Installer 2.2.4
Riru Ed Xposed 0.3.1.7_beta
Riru Core 18

Problem:
QuickTap launcher not working.

Just before uploading this, I updated to the latest version, beta 8, still no success. Everything else that I use works fine even the Per-finger launcher. If there is any problem with how I submitted the logs please let me know and how I can help to speed up the process.

Thanks in advance.

---------------------------

Error.log copy
04-20 09:58:57.126  1144  1144 I EdXposed-Bridge: GB:Is AOSP forced: false
04-20 09:59:01.261   689   689 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-gFjgd3fHHbbF5jJ6tv8egg==/base.apk
04-20 09:59:01.267  1897  1928 W XSharedPreferences: getSharedPreferences
04-20 09:59:01.267  1897  1928 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-20 09:59:01.267  1897  1928 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-20 09:59:01.267  1897  1928 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-20 09:59:01.267  1897  1928 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-20 09:59:01.267  1897  1928 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-20 09:59:01.267  1897  1928 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-20 09:59:01.267  1897  1927 W XSharedPreferences: getSharedPreferences
04-20 09:59:01.267  1897  1927 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-20 09:59:01.267  1897  1927 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-20 09:59:01.267  1897  1927 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-20 09:59:01.267  1897  1927 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-20 09:59:01.267  1897  1927 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-20 09:59:01.267  1897  1927 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-20 09:59:01.340   689   689 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.systemui.statusbar.KeyguardIndicationController#-get3(com.android.systemui.statusbar.KeyguardIndicationController)#exact
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModLowBatteryWarning.init(ModLowBatteryWarning.java:176)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:152)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:74)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
04-20 09:59:01.349  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-20 09:59:01.350   689  1971 W XSharedPreferences: getSharedPreferences
04-20 09:59:01.350   689  1971 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-20 09:59:01.350   689  1971 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-20 09:59:01.350   689  1971 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-20 09:59:01.350   689  1971 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-20 09:59:01.350   689  1971 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-20 09:59:01.350   689  1971 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-20 09:59:01.351   689  1972 W XSharedPreferences: getSharedPreferences
04-20 09:59:01.351   689  1972 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
04-20 09:59:01.351   689  1972 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
04-20 09:59:01.351   689  1972 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
04-20 09:59:01.351   689  1972 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
04-20 09:59:01.351   689  1972 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
04-20 09:59:01.351   689  1972 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.oneplus.dialer.settings.OPDialerSettingsActivity
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModDialerOOS.initDialer(ModDialerOOS.java:62)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:226)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:74)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1300(ActivityThread.java:207)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.oneplus.dialer.settings.OPDialerSettingsActivity
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at java.lang.Class.classForName(Native Method)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at java.lang.Class.forName(Class.java:453)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	... 15 more
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oneplus.dialer.settings.OPDialerSettingsActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/qcnvitems.jar", zip file "/system/priv-app/Dialer/Dialer.apk"],nativeLibraryDirectories=[/system/priv-app/Dialer/lib/arm64, /system/lib64, /system/lib64]]
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	... 19 more
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 	Suppressed: java.io.IOException: No original dex files found for dex location /system/framework/qcnvitems.jar
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexFile.<init>(DexFile.java:101)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexFile.<init>(DexFile.java:75)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:83)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:735)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:818)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:66)
04-20 09:59:02.935  2514  2514 E EdXposed-Bridge: 		... 8 more
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.systemui.BatteryMeterView#onFastChargeChanged(boolean)#exact
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.createHooks(BatteryStyleController.java:338)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.<init>(BatteryStyleController.java:90)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.<init>(BatteryStyleController.java:76)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.prepareBatteryStyle(ModStatusBar.java:405)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.access$2300(ModStatusBar.java:60)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar$4.afterHookedMethod(ModStatusBar.java:592)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:127)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.statusbar.phone.StatusBar.addStatusBarWindow(StatusBar.java:3450)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:3446)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:872)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:105)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:71)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.SystemBars.start(SystemBars.java:42)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:196)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:135)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:48)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:105)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3667)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1500(ActivityThread.java:207)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
04-20 09:59:03.371  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.systemui.BatteryMeterView#onFastChargeChanged(boolean)#exact
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:333)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.createHooks(BatteryStyleController.java:338)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.<init>(BatteryStyleController.java:90)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.<init>(BatteryStyleController.java:76)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.prepareBatteryStyle(ModStatusBar.java:405)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.access$2300(ModStatusBar.java:60)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar$5.afterHookedMethod(ModStatusBar.java:645)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:142)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.statusbar.phone.StatusBar.lambda$makeStatusBarView$3(StatusBar.java:1039)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBar$TPJyILujZ88K3rKFmgzHGHpbtLo.onFragmentViewCreated(Unknown Source:2)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.fragments.FragmentHostManager.lambda$onFragmentViewCreated$0(FragmentHostManager.java:136)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.fragments.-$$Lambda$FragmentHostManager$OsWXqtcfRJZBAvEEeN8CG6EN5T4.accept(Unknown Source:6)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at java.util.ArrayList.forEach(ArrayList.java:1262)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.fragments.FragmentHostManager.onFragmentViewCreated(FragmentHostManager.java:136)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.fragments.FragmentHostManager.access$000(FragmentHostManager.java:46)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.systemui.fragments.FragmentHostManager$1.onFragmentViewCreated(FragmentHostManager.java:76)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.dispatchOnFragmentViewCreated(FragmentManager.java:3336)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1309)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:873)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
04-20 09:59:03.634  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.systemui.BatteryMeterView#onFastChargeChanged(boolean)#exact
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:333)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.createHooks(BatteryStyleController.java:338)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.BatteryStyleController.<init>(BatteryStyleController.java:90)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.prepareBatteryStyleHeader(ModStatusBar.java:424)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar.access$3400(ModStatusBar.java:60)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.ceco.pie.gravitybox.ModStatusBar$6.afterHookedMethod(ModStatusBar.java:661)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:157)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:873)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
04-20 09:59:03.732  1897  1897 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by C3C0** [comment]
QuickTap in fingerprint launcher is based on "finger partially detected" error so it requires some practice and even can depend on hardware. Try various methods, such as quickly swiping over the sensor instead of tapping, etc. There is not much I can do on my side.
