### ISSUE TITLE
SystemUI crash on minute changes with Android 9.0

### ISSUE THREAD

**Issue by ghost** [GravityBox/GravityBox#2013]
I am using LineageOS 2019-08-23 on klte. I just upgraded. Every time a minute change happens, SystemUI will crash. Here is a logcat of the crash. Seems like something related to the clock changed/relocated in SystemUI.
```
08-26 02:49:00.143  6449  6449 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x96fdcfb4 in tid 6449 (ndroid.systemui), pid 6449 (ndroid.systemui)
08-26 02:49:00.211   810   821 I WifiService: startScan uid=1000
08-26 02:49:00.212   509   509 W wificond: Copy constructor is only used for unit tests
08-26 02:49:00.212   509   509 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
08-26 02:49:00.213   509   509 W wificond: Copy constructor is only used for unit tests
08-26 02:49:00.213   509   509 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
08-26 02:49:00.213   509   509 W wificond: Copy constructor is only used for unit tests
08-26 02:49:00.213   509   509 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
08-26 02:49:00.218  7008  7008 W crash_dump32: failed to fetch registers for thread 6454: I/O error
08-26 02:49:00.220  7008  7008 W crash_dump32: failed to fetch registers for thread 6455: I/O error
08-26 02:49:00.221  7008  7008 W crash_dump32: failed to fetch registers for thread 6456: I/O error
08-26 02:49:00.222  7008  7008 W crash_dump32: failed to fetch registers for thread 6457: I/O error
08-26 02:49:00.222  7008  7008 W crash_dump32: failed to fetch registers for thread 6458: I/O error
08-26 02:49:00.224  7008  7008 W crash_dump32: failed to fetch registers for thread 6459: I/O error
08-26 02:49:00.224  7008  7008 W crash_dump32: failed to fetch registers for thread 6460: I/O error
08-26 02:49:00.224  7008  7008 W crash_dump32: failed to fetch registers for thread 6461: I/O error
08-26 02:49:00.225  7008  7008 W crash_dump32: failed to fetch registers for thread 6463: I/O error
08-26 02:49:00.225  7008  7008 W crash_dump32: failed to fetch registers for thread 6474: I/O error
08-26 02:49:00.225  7008  7008 W crash_dump32: failed to fetch registers for thread 6475: I/O error
08-26 02:49:00.226  7008  7008 W crash_dump32: failed to fetch registers for thread 6476: I/O error
08-26 02:49:00.226  7008  7008 W crash_dump32: failed to fetch registers for thread 6478: I/O error
08-26 02:49:00.226  7008  7008 W crash_dump32: failed to fetch registers for thread 6482: I/O error
08-26 02:49:00.227  7008  7008 W crash_dump32: failed to fetch registers for thread 6483: I/O error
08-26 02:49:00.227  7008  7008 W crash_dump32: failed to fetch registers for thread 6485: I/O error
08-26 02:49:00.227  7008  7008 W crash_dump32: failed to fetch registers for thread 6499: I/O error
08-26 02:49:00.228  7008  7008 W crash_dump32: failed to fetch registers for thread 6503: I/O error
08-26 02:49:00.228  7008  7008 W crash_dump32: failed to fetch registers for thread 6504: I/O error
08-26 02:49:00.229  7008  7008 W crash_dump32: failed to fetch registers for thread 6506: I/O error
08-26 02:49:00.229  7008  7008 W crash_dump32: failed to fetch registers for thread 6507: I/O error
08-26 02:49:00.230  7008  7008 W crash_dump32: failed to fetch registers for thread 6508: I/O error
08-26 02:49:00.230  7008  7008 W crash_dump32: failed to fetch registers for thread 6509: I/O error
08-26 02:49:00.231  7008  7008 W crash_dump32: failed to fetch registers for thread 6516: I/O error
08-26 02:49:00.231  7008  7008 W crash_dump32: failed to fetch registers for thread 6520: I/O error
08-26 02:49:00.231  7008  7008 W crash_dump32: failed to fetch registers for thread 6523: I/O error
08-26 02:49:00.232  7008  7008 W crash_dump32: failed to fetch registers for thread 6524: I/O error
08-26 02:49:00.232  7008  7008 W crash_dump32: failed to fetch registers for thread 6525: I/O error
08-26 02:49:00.232  7008  7008 W crash_dump32: failed to fetch registers for thread 6526: I/O error
08-26 02:49:00.234  7008  7008 W crash_dump32: failed to fetch registers for thread 6529: I/O error
08-26 02:49:00.234  7008  7008 W crash_dump32: failed to fetch registers for thread 6540: I/O error
08-26 02:49:00.234  7008  7008 W crash_dump32: failed to fetch registers for thread 6543: I/O error
08-26 02:49:00.235  7008  7008 W crash_dump32: failed to fetch registers for thread 6553: I/O error
08-26 02:49:00.235  7008  7008 W crash_dump32: failed to fetch registers for thread 6712: I/O error
08-26 02:49:00.235  7008  7008 W crash_dump32: failed to fetch registers for thread 6725: I/O error
08-26 02:49:00.235  7008  7008 W crash_dump32: failed to fetch registers for thread 6946: I/O error
08-26 02:49:00.236  7008  7008 W crash_dump32: failed to fetch registers for thread 6947: I/O error
08-26 02:49:00.236  7008  7008 W crash_dump32: failed to fetch registers for thread 6948: I/O error
08-26 02:49:00.236  7008  7008 W crash_dump32: failed to fetch registers for thread 6949: I/O error
08-26 02:49:00.236  7008  7008 W crash_dump32: failed to fetch registers for thread 6950: I/O error
08-26 02:49:00.285  7008  7008 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-26 02:49:00.286   519   519 I /system/bin/tombstoned: received crash request for pid 6449
08-26 02:49:00.288  7008  7008 I crash_dump32: performing dump of process 6449 (target tid = 6449)
08-26 02:49:00.325  7008  7008 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-26 02:49:00.325  7008  7008 F DEBUG   : LineageOS Version: '16.0-20190823-NIGHTLY-klte'
08-26 02:49:00.325  7008  7008 F DEBUG   : Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
08-26 02:49:00.325  7008  7008 F DEBUG   : Revision: '14'
08-26 02:49:00.325  7008  7008 F DEBUG   : ABI: 'arm'
08-26 02:49:00.325  7008  7008 F DEBUG   : pid: 6449, tid: 6449, name: ndroid.systemui  >>> com.android.systemui <<<
08-26 02:49:00.325  7008  7008 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x96fdcfb4
08-26 02:49:00.326  7008  7008 F DEBUG   :     r0  00000000  r1  00000000  r2  67e3a7b3  r3  0000008b
08-26 02:49:00.326  7008  7008 F DEBUG   :     r4  6fcfae58  r5  96fdcfb4  r6  00000000  r7  00000000
08-26 02:49:00.326  7008  7008 F DEBUG   :     r8  af11a4e4  r9  ab3768a8  r10 96fdcfb0  r11 0000bad0
08-26 02:49:00.326  7008  7008 F DEBUG   :     ip  0000006e  sp  bee5d260  lr  ab15a6ff  pc  ab15a74a
08-26 02:49:00.519  7008  7008 F DEBUG   : 
08-26 02:49:00.519  7008  7008 F DEBUG   : backtrace:
08-26 02:49:00.519  7008  7008 F DEBUG   :     #00 pc 0026174a  /system/lib/libart.so (offset 0x1a6000) (art::ProfilingInfo::AddInvokeInfo(unsigned int, art::mirror::Class*)+86)
08-26 02:49:00.519  7008  7008 F DEBUG   :     #01 pc 003ec361  /system/lib/libart.so (offset 0x2b6000) (MterpInvokeVirtual+384)
08-26 02:49:00.519  7008  7008 F DEBUG   :     #02 pc 0040af94  /system/lib/libart.so (offset 0x2b6000) (ExecuteMterpImpl+14228)
08-26 02:49:00.519  7008  7008 F DEBUG   :     #03 pc 00386f36  /system/priv-app/SystemUI/SystemUI.apk (com.android.systemui.statusbar.policy.Clock.getSmallTime+278)
08-26 02:49:00.519  7008  7008 F DEBUG   :     #04 pc 001c83d7  /system/lib/libart.so (offset 0x1a6000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1701902759+354)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #05 pc 001ccd0f  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #06 pc 001e489f  /system/lib/libart.so (offset 0x1a6000) (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+674)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #07 pc 003ee5a1  /system/lib/libart.so (offset 0x2b6000) (MterpInvokeStaticRange+100)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #08 pc 0040b414  /system/lib/libart.so (offset 0x2b6000) (ExecuteMterpImpl+15380)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #09 pc 000003fa  /dev/ashmem/dalvik-DEX data (deleted) (EdHooker95.hook+210)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #10 pc 001c83d7  /system/lib/libart.so (offset 0x1a6000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1701902759+354)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #11 pc 001ccc5b  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #12 pc 003dfc33  /system/lib/libart.so (offset 0x2b6000) (artQuickToInterpreterBridge+882)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #13 pc 0041c6ff  /system/lib/libart.so (offset 0x2b6000) (art_quick_to_interpreter_bridge+30)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #14 pc 00418175  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_stub_internal+68)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #15 pc 003f16e5  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_stub+224)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #16 pc 000a100d  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #17 pc 001e8d17  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+230)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #18 pc 001e3a21  /system/lib/libart.so (offset 0x1a6000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+784)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #19 pc 003ed231  /system/lib/libart.so (offset 0x2b6000) (MterpInvokeDirect+196)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #20 pc 0040b094  /system/lib/libart.so (offset 0x2b6000) (ExecuteMterpImpl+14484)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #21 pc 00387724  /system/priv-app/SystemUI/SystemUI.apk (com.android.systemui.statusbar.policy.Clock.updateClock+36)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #22 pc 001c83d7  /system/lib/libart.so (offset 0x1a6000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1701902759+354)
08-26 02:49:00.520  7008  7008 F DEBUG   :     #23 pc 001ccd0f  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #24 pc 001e3a0b  /system/lib/libart.so (offset 0x1a6000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+762)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #25 pc 003ec39b  /system/lib/libart.so (offset 0x2b6000) (MterpInvokeVirtual+442)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #26 pc 0040af94  /system/lib/libart.so (offset 0x2b6000) (ExecuteMterpImpl+14228)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #27 pc 00386b78  /system/priv-app/SystemUI/SystemUI.apk (com.android.systemui.statusbar.policy.Clock$2.lambda$onReceive$2+4)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #28 pc 001c83d7  /system/lib/libart.so (offset 0x1a6000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1701902759+354)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #29 pc 001ccd0f  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+146)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #30 pc 001e3a0b  /system/lib/libart.so (offset 0x1a6000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+762)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #31 pc 003ed37b  /system/lib/libart.so (offset 0x2b6000) (MterpInvokeStatic+130)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #32 pc 0040b114  /system/lib/libart.so (offset 0x2b6000) (ExecuteMterpImpl+14612)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #33 pc 00383334  /system/priv-app/SystemUI/SystemUI.apk (com.android.systemui.statusbar.policy.-$$Lambda$Clock$2$mOTwR4Tu5xrxBBIUbNE9701lx-4.run+4)
08-26 02:49:00.521  7008  7008 F DEBUG   :     #34 pc 001c83d7  /system/lib/libart.so (offset 0x1a6000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1701902759+354)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #35 pc 001ccc5b  /system/lib/libart.so (offset 0x1a6000) (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #36 pc 003dfc33  /system/lib/libart.so (offset 0x2b6000) (artQuickToInterpreterBridge+882)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #37 pc 0041c6ff  /system/lib/libart.so (offset 0x2b6000) (art_quick_to_interpreter_bridge+30)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #38 pc 008fb5d9  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.os.Handler.dispatchMessage+64)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #39 pc 008fdd8f  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.os.Looper.loop+1286)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #40 pc 00743589  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.app.ActivityThread.main+664)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #41 pc 00418175  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_stub_internal+68)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #42 pc 003f17e7  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_static_stub+222)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #43 pc 000a101f  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #44 pc 00351131  /system/lib/libart.so (offset 0x2b6000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #45 pc 00352583  /system/lib/libart.so (offset 0x2b6000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+962)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #46 pc 00303251  /system/lib/libart.so (offset 0x2b6000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #47 pc 0010c1f7  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #48 pc 009f729b  /system/framework/arm/boot-framework.oat (offset 0x383000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #49 pc 009fd1ad  /system/framework/arm/boot-framework.oat (offset 0x383000) (com.android.internal.os.ZygoteInit.main+2884)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #50 pc 00418175  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_stub_internal+68)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #51 pc 003f17e7  /system/lib/libart.so (offset 0x2b6000) (art_quick_invoke_static_stub+222)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #52 pc 000a101f  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #53 pc 00351131  /system/lib/libart.so (offset 0x2b6000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #54 pc 00350f45  /system/lib/libart.so (offset 0x2b6000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+300)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #55 pc 00294bf9  /system/lib/libart.so (offset 0x1a6000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+476)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #56 pc 0006ccbf  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+38)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #57 pc 0006ef29  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+460)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #58 pc 00001989  /system/bin/app_process32 (main+728)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #59 pc 0008ccb9  /system/lib/libc.so (__libc_init+48)
08-26 02:49:00.522  7008  7008 F DEBUG   :     #60 pc 00001671  /system/bin/app_process32 (_start_main+40)
08-26 02:49:00.523  7008  7008 F DEBUG   :     #61 pc 0000031e  <anonymous:af117000>
08-26 02:49:00.735  7008  7008 E crash_dump32: AM data write failed: Broken pipe
08-26 02:49:00.737   519   519 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_09
08-26 02:49:00.739  6449  6449 W ndroid.systemui: type=1701 audit(0.0:196): auid=4294967295 uid=10027 gid=10027 ses=4294967295 subj=u:r:platform_app:s0:c512,c768 reason="memory violation" sig=11
08-26 02:49:00.765   810   829 I BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
08-26 02:49:00.789   810  1585 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=30, [ Transports: WIFI Capabilities: NOT_VPN Unwanted: ] ], android.os.BinderProxy@2856675)
08-26 02:49:00.789   810  4822 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=31, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10027] ], android.os.BinderProxy@b82760a)
08-26 02:49:00.789   810  4070 I StatusBarManagerService: binder died for pkg=null
08-26 02:49:00.789   810  1582 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=32, [] ], android.os.BinderProxy@c3f7e7b)
08-26 02:49:00.790   810  4070 W AudioService: Current remote volume controller died, unregistering
08-26 02:49:00.790   810  1062 W WifiService: Client connection lost with reason: 4
08-26 02:49:00.790   810  4070 W VolumeController: Error calling dismiss
08-26 02:49:00.790   810  4070 W VolumeController: android.os.DeadObjectException
08-26 02:49:00.790   810  4070 W VolumeController:      at android.os.BinderProxy.transactNative(Native Method)
08-26 02:49:00.790   810  4070 W VolumeController:      at android.os.BinderProxy.transact(Binder.java:1129)
08-26 02:49:00.790   810  4070 W VolumeController:      at android.media.IVolumeController$Stub$Proxy.dismiss(IVolumeController.java:174)
08-26 02:49:00.790   810  4070 W VolumeController:      at com.android.server.audio.AudioService$VolumeController.postDismiss(AudioService.java:7535)
08-26 02:49:00.790   810  4070 W VolumeController:      at com.android.server.audio.AudioService.setVolumeController(AudioService.java:7383)
08-26 02:49:00.790   810  4070 W VolumeController:      at com.android.server.audio.AudioService$4.binderDied(AudioService.java:7392)
08-26 02:49:00.790   810  4070 W VolumeController:      at android.os.BinderProxy.sendDeathNotice(Binder.java:1195)
08-26 02:49:00.790   810   825 W UsageStatsService: Event reported without a package name
08-26 02:49:00.791   810  5394 D NotificationListeners: Removing active service ComponentInfo{com.android.systemui/com.android.systemui.statusbar.NotificationListener}
08-26 02:49:00.791   810   810 W WallpaperManagerService: Wallpaper service gone: ComponentInfo{com.android.systemui/com.android.systemui.ImageWallpaper}
08-26 02:49:00.791   810  1066 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=31, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10027] ] (release request)
08-26 02:49:00.791   810  1584 W FingerprintService: stopAuthentication: already cancelled!
08-26 02:49:00.792   810  1485 E FingerprintService: Lockout reset callback binder died
08-26 02:49:00.794   810   820 I WindowManager: WIN DEATH: Window{e05deb u0 com.android.systemui.ImageWallpaper}
08-26 02:49:00.798   810   889 W InputDispatcher: channel '9821ddd DockedStackDivider (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-26 02:49:00.798   810   889 E InputDispatcher: channel '9821ddd DockedStackDivider (server)' ~ Channel is unrecoverably broken and will be disposed!
08-26 02:49:00.798   810   889 W InputDispatcher: channel '3400c49 AssistPreviewPanel (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-26 02:49:00.798   810   889 E InputDispatcher: channel '3400c49 AssistPreviewPanel (server)' ~ Channel is unrecoverably broken and will be disposed!
08-26 02:49:00.799   810   889 W InputDispatcher: channel '9b27bc3 StatusBar (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-26 02:49:00.799   810   889 E InputDispatcher: channel '9b27bc3 StatusBar (server)' ~ Channel is unrecoverably broken and will be disposed!
08-26 02:49:00.800   810   821 I WindowManager: WIN DEATH: Window{3400c49 u0 AssistPreviewPanel}
08-26 02:49:00.800   810   821 W InputDispatcher: Attempted to unregister already unregistered input channel '3400c49 AssistPreviewPanel (server)'
08-26 02:49:00.806   448   487 W SurfaceFlinger: Attempting to destroy on removed layer: 3400c49 AssistPreviewPanel#0
08-26 02:49:00.808   810  1582 I WindowManager: WIN DEATH: Window{9b27bc3 u0 StatusBar}
08-26 02:49:00.808   810  1582 W InputDispatcher: Attempted to unregister already unregistered input channel '9b27bc3 StatusBar (server)'
08-26 02:49:00.812   448  1208 D SurfaceFlinger: duplicate layer name: changing Surface(name=96c8623 bydemir)/@0x62a969b - animation-leash to Surface(name=96c8623 bydemir)/@0x62a969b - animation-leash#1
08-26 02:49:00.822   810  1484 I WindowManager: WIN DEATH: Window{9821ddd u0 DockedStackDivider}
08-26 02:49:00.822   810  1484 W InputDispatcher: Attempted to unregister already unregistered input channel '9821ddd DockedStackDivider (server)'
08-26 02:49:00.841   419   419 I Zygote  : Process 6449 exited due to signal (11)
08-26 02:49:00.855   810  1453 I ActivityManager: Process com.android.systemui (pid 6449) has died: pers PER 
08-26 02:49:00.855   810  1453 W ActivityManager: Scheduling restart of crashed service com.android.systemui/.SystemUIService in 0ms
08-26 02:49:00.855   810  1453 W ActivityManager: Scheduling restart of crashed service com.android.systemui/.keyguard.KeyguardService in 0ms
08-26 02:49:00.856   810  1453 W ActivityManager: Scheduling restart of crashed service com.android.systemui/.ImageWallpaper in 0ms
08-26 02:49:00.856   810  1453 W ActivityManager: Re-adding persistent process ProcessRecord{acc9311 6449:com.android.systemui/u0a27}
08-26 02:49:00.858   810   827 W libprocessgroup: kill(-6449, 9) failed: No such process
08-26 02:49:00.858   810   827 I libprocessgroup: Successfully killed process cgroup uid 10027 pid 6449 in 0ms
08-26 02:49:00.886   810   826 I ActivityManager: Start proc 7024:com.android.systemui/u0a27 for restart com.android.systemui
08-26 02:49:00.891   810   889 I InputDispatcher: Dropping event because there is no touchable window at (692, 1687).
08-26 02:49:00.922  7024  7024 E ndroid.systemu: Not starting debugger since process cannot load the jdwp agent.
08-26 02:49:00.922  7024  7024 V Riru    : edxp: forkAndSpecializePost
08-26 02:49:00.959  7024  7024 I ndroid.systemu: The ClassLoaderContext is a special shared library.
```

**Comment by TheSamehMagdy** [comment]
Exact same issue on LineageOS 16 on Redmi Note 7.
Disabling the clock master switch fixes it for now.

**Comment by C3C0** [comment]
That crash is at lower level - at Android Runtime level (libart) which indicates some kind of incompatibility issue in EdXposed framework itself.
