### ISSUE TITLE
Quick unlock not working

### ISSUE THREAD

**Issue by achozex** [GravityBox/GravityBox#2042]
GravityBox Version: 10.0.0-beta-6
EdXposed Version: SandHook v0.4.6.0_beta
Device : oneplus7t Pro

the phone does not unlock automatically after inserting pin

**Comment by C3C0** [comment]
EdXposed module log needed. Make sure you have "Error logging" enabled in About section of GravityBox settings before posting the log.

**Comment by achozex** [comment]
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
--------- beginning of information
Android version: 10
Android sdk: 29
Android build: QKQ1.190716.003
Fingerprint: OnePlus/OnePlus7TPro/OnePlus7TPro:10/QKQ1.190716.003/1912060020:user/release-keys
ROM build description: OnePlus7TPro-user 10 QKQ1.190716.003 1912060020 release-keys
EdXposed Version: v0.4.6.1 (4489)-rtiihway (SandHook) (api: 90.0)
Architecture: arm64-v8a
Device: OnePlus7TPro
Manufacture: OnePlus
Brand: OnePlus
Product: OnePlus7TPro
Riru: v19.5 (27) (api: 4)
Magisk: 20.2:MAGISKSU (20200)
--------- beginning of main
--------- beginning of system
01-14 14:22:30.327   828   828 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-14 14:22:30.327   828   828 I EdXposed: Start to install inline hooks
01-14 14:22:30.327   828   828 I EdXposed: Using api level 29
01-14 14:22:30.327   828   828 I EdXposed: Start to install Riru hook
01-14 14:22:30.335   828   828 I EdXposed: Riru hooks installed
01-14 14:22:30.440   829   829 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-14 14:22:30.440   829   829 I EdXposed: Start to install inline hooks
01-14 14:22:30.440   829   829 I EdXposed: Using api level 29
01-14 14:22:30.440   829   829 I EdXposed: Start to install Riru hook
01-14 14:22:30.451   829   829 I EdXposed: Riru hooks installed
01-14 14:22:30.492   828   828 I EdXposed: ART hooks installed
01-14 14:22:30.492   828   828 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-14 14:22:30.492   828   828 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-14 14:22:30.617   829   829 I EdXposed: ART hooks installed
01-14 14:22:30.617   829   829 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-14 14:22:30.617   829   829 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-14 14:22:30.839   829   829 I EdXposed: using installer org.meowcat.edxposed.manager
01-14 14:22:30.839   829   829 I EdXposed: black/white list mode: false, using whitelist: false
01-14 14:22:30.839   829   829 I EdXposed: dynamic modules mode: false
01-14 14:22:30.839   829   829 I EdXposed: resources hook: true
01-14 14:22:30.839   829   829 I EdXposed: deopt boot image: false
01-14 14:22:30.850   828   828 I EdXposed: using installer org.meowcat.edxposed.manager
01-14 14:22:30.850   828   828 I EdXposed: black/white list mode: false, using whitelist: false
01-14 14:22:30.850   828   828 I EdXposed: dynamic modules mode: false
01-14 14:22:30.850   828   828 I EdXposed: resources hook: true
01-14 14:22:30.850   828   828 I EdXposed: deopt boot image: false
01-14 14:22:33.356   828   828 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-g4H9kKwhpIzJVozf3eppLw==/base.apk
01-14 14:22:33.459   828   828 I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Hardware: qcom
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Product: OnePlus7TPro
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Device manufacturer: OnePlus
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Device brand: OnePlus
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Device model: HD1913
01-14 14:22:33.466   828   828 I EdXposed-Bridge: GB:Device: OnePlus7TPro
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Device type: phone
01-14 14:22:33.468   828  1650 W XSharedPreferences: getSharedPreferences
01-14 14:22:33.468   828  1650 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:33.468   828  1650 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:33.468   828  1650 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:33.468   828  1650 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:33.468   828  1650 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:33.468   828  1650 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:33.468   828  1652 W XSharedPreferences: getSharedPreferences
01-14 14:22:33.468   828  1652 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:33.468   828  1652 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:33.468   828  1652 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:33.468   828  1652 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:33.468   828  1652 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:33.468   828  1652 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Is MTK device: false
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Is Xperia device: false
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Is Moto XT device: false
01-14 14:22:33.468   828  1651 W XSharedPreferences: getSharedPreferences
01-14 14:22:33.468   828  1651 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:33.468   828  1651 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:33.468   828  1651 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:33.468   828  1651 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:33.468   828  1651 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:33.468   828  1651 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Is OxygenOS ROM: true
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Has telephony support: true
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Has Gemini support: false
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Android SDK: 29
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Android Release: 10
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:ROM: HD1913_14_191206
01-14 14:22:33.468   828   828 I EdXposed-Bridge: GB:Error logging: true
01-14 14:22:33.863  1657  1657 I EdXposed-Bridge: GB:Is AOSP forced: false
01-14 14:22:38.148  2434  2487 W XSharedPreferences: getSharedPreferences
01-14 14:22:38.148  2434  2487 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:38.148  2434  2487 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:38.148  2434  2487 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:38.148  2434  2487 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:38.148  2434  2487 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:38.148  2434  2487 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:38.153  2434  2488 W XSharedPreferences: getSharedPreferences
01-14 14:22:38.153  2434  2488 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:38.153  2434  2488 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:38.153  2434  2488 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:38.153  2434  2488 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:38.153  2434  2488 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:38.153  2434  2488 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:38.158  2434  2486 W XSharedPreferences: getSharedPreferences
01-14 14:22:38.158  2434  2486 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:38.158  2434  2486 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:38.158  2434  2486 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:38.158  2434  2486 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:38.158  2434  2486 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:38.158  2434  2486 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:42.414  2434  3415 W XSharedPreferences: getSharedPreferences
01-14 14:22:42.414  2434  3415 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:42.414  2434  3415 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:42.414  2434  3415 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:42.414  2434  3415 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:42.414  2434  3415 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:42.414  2434  3415 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:38.054  2434  3668 W XSharedPreferences: getSharedPreferences
01-14 14:22:38.054  2434  3668 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:38.054  2434  3668 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:38.054  2434  3668 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:38.054  2434  3668 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:38.054  2434  3668 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:38.054  2434  3668 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
--------- beginning of crash
01-14 14:22:54.647   829   829 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-g4H9kKwhpIzJVozf3eppLw==/base.apk
01-14 14:22:54.764   829   829 I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
01-14 14:22:54.780   829  5747 W XSharedPreferences: getSharedPreferences
01-14 14:22:54.780   829  5747 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:54.780   829  5747 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:54.780   829  5747 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:54.780   829  5747 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:54.780   829  5747 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:54.780   829  5747 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:54.780   829  5748 W XSharedPreferences: getSharedPreferences
01-14 14:22:54.780   829  5748 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:54.780   829  5748 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:54.780   829  5748 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:54.780   829  5748 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:54.780   829  5748 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:54.780   829  5748 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:22:54.783   829  5746 W XSharedPreferences: getSharedPreferences
01-14 14:22:54.783   829  5746 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:22:54.783   829  5746 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:22:54.783   829  5746 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:22:54.783   829  5746 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:22:54.783   829  5746 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:22:54.783   829  5746 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:23:18.678  2434  8926 W XSharedPreferences: getSharedPreferences
01-14 14:23:18.678  2434  8926 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:23:18.678  2434  8926 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:23:18.678  2434  8926 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:23:18.678  2434  8926 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:23:18.678  2434  8926 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:23:18.678  2434  8926 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-14 14:24:58.510  2434 15169 W XSharedPreferences: getSharedPreferences
01-14 14:24:58.510  2434 15169 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-14 14:24:58.510  2434 15169 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-14 14:24:58.510  2434 15169 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-14 14:24:58.510  2434 15169 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-14 14:24:58.510  2434 15169 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-14 14:24:58.510  2434 15169 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)

**Comment by achozex** [comment]
I didn't have permission for modules log, idk why but here's the log for it


--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: OnePlus
Brand: OnePlus
Device: OnePlus7TPro
Product: OnePlus7TPro
Model: HD1913
Fingerprint: OnePlus/OnePlus7TPro/OnePlus7TPro:10/QKQ1.190716.003/1912060020:user/release-keys
ROM description: OnePlus7TPro-user 10 QKQ1.190716.003 1912060020 release-keys
Architecture: arm64-v8a
Android build: QKQ1.190716.003
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.1 (4497)-selhygwy (SandHook)
EdXposed api: 90.0
Riru version: v19.5 (27)
Riru api: 4
Magisk: 20.3:MAGISKSU (20300)
--------- beginning of main
--------- beginning of system
01-22 10:11:13.071   850   850 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-g4H9kKwhpIzJVozf3eppLw==/base.apk
01-22 10:11:13.145   850   850 I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Hardware: qcom
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Product: OnePlus7TPro
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Device manufacturer: OnePlus
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Device brand: OnePlus
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Device model: HD1913
01-22 10:11:13.151   850   850 I EdXposed-Bridge: GB:Device: OnePlus7TPro
01-22 10:11:13.151   850  1702 W XSharedPreferences: getSharedPreferences
01-22 10:11:13.151   850  1702 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:13.151   850  1702 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:13.151   850  1702 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:13.151   850  1702 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:13.151   850  1702 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:13.151   850  1702 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:13.151   850  1703 W XSharedPreferences: getSharedPreferences
01-22 10:11:13.151   850  1703 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:13.151   850  1703 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:13.151   850  1703 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:13.151   850  1703 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:13.151   850  1703 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:13.151   850  1703 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:13.151   850  1704 W XSharedPreferences: getSharedPreferences
01-22 10:11:13.151   850  1704 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:13.151   850  1704 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:13.151   850  1704 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:13.151   850  1704 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:13.151   850  1704 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:13.151   850  1704 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Device type: phone
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Is MTK device: false
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Is Xperia device: false
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Is Moto XT device: false
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Is OxygenOS ROM: true
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Has telephony support: true
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Has Gemini support: false
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Android SDK: 29
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Android Release: 10
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:ROM: HD1913_14_191206
01-22 10:11:13.152   850   850 I EdXposed-Bridge: GB:Error logging: true
01-22 10:11:13.587  1706  1706 I EdXposed-Bridge: GB:Is AOSP forced: false
01-22 10:11:17.484  2451  2510 W XSharedPreferences: getSharedPreferences
01-22 10:11:17.484  2451  2510 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:17.484  2451  2510 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:17.484  2451  2510 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:17.484  2451  2510 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:17.484  2451  2510 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:17.484  2451  2510 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:17.484  2451  2508 W XSharedPreferences: getSharedPreferences
01-22 10:11:17.484  2451  2508 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:17.484  2451  2508 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:17.484  2451  2508 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:17.484  2451  2508 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:17.484  2451  2508 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:17.484  2451  2508 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:17.484  2451  2507 W XSharedPreferences: getSharedPreferences
01-22 10:11:17.484  2451  2507 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:17.484  2451  2507 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:17.484  2451  2507 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:17.484  2451  2507 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:17.484  2451  2507 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:17.484  2451  2507 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:21.561  2451  3452 W XSharedPreferences: getSharedPreferences
01-22 10:11:21.561  2451  3452 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:21.561  2451  3452 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:21.561  2451  3452 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:21.561  2451  3452 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:21.561  2451  3452 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:21.561  2451  3452 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:23.107  2451  3628 W XSharedPreferences: getSharedPreferences
01-22 10:11:23.107  2451  3628 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:23.107  2451  3628 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:23.107  2451  3628 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:23.107  2451  3628 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:23.107  2451  3628 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:23.107  2451  3628 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
--------- beginning of crash
01-22 10:11:40.764   851   851 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.q.gravitybox-g4H9kKwhpIzJVozf3eppLw==/base.apk
01-22 10:11:40.943   851   851 I EdXposed-Bridge:   Loading class com.ceco.q.gravitybox.GravityBox
01-22 10:11:40.956   851  5201 W XSharedPreferences: getSharedPreferences
01-22 10:11:40.956   851  5201 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:40.956   851  5201 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:40.956   851  5201 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:40.956   851  5201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:40.956   851  5201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:40.956   851  5201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:40.958   851  5202 W XSharedPreferences: getSharedPreferences
01-22 10:11:40.958   851  5202 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:40.958   851  5202 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:40.958   851  5202 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:40.958   851  5202 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:40.958   851  5202 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:40.958   851  5202 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:40.961   851  5200 W XSharedPreferences: getSharedPreferences
01-22 10:11:40.961   851  5200 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:40.961   851  5200 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:40.961   851  5200 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:40.961   851  5200 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:40.961   851  5200 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:40.961   851  5200 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 10:11:50.912  2451  7201 W XSharedPreferences: getSharedPreferences
01-22 10:11:50.912  2451  7201 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 10:11:50.912  2451  7201 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-22 10:11:50.912  2451  7201 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-22 10:11:50.912  2451  7201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 10:11:50.912  2451  7201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 10:11:50.912  2451  7201 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)

**Comment by C3C0** [comment]
Log does not show any issues that could be related.
Make sure you have proper PIN length set in GravityBox / Lockscreen settings.
Also note, that this feature does not apply to SIM pin. Only to standard unlock PIN.
