### ISSUE TITLE
New style traffic meter in roms not supported

### ISSUE THREAD

**Issue by usamaiqbal1177** [GravityBox/GravityBox#2047]
I'm using latest magisk-EdXposed-YAHFA-v0.4.6.1 (4488)-iaodllck-release.zip
Gravity box is breaking system UI. I can't boot properly. 
Android 10
Redmi note 4x
[boot-1970-03-30-01-28-04.log](https://github.com/GravityBox/GravityBox/files/4021690/boot-1970-03-30-01-28-04.log)

This log was created by log catcher in /data/local/boot

**Comment by usamaiqbal1177** [comment]
@C3C0 can u please see this?

**Comment by C3C0** [comment]
It's crashing due to some mysterious "NetworkTrafficSB" element in system icon area.
I don't know where this element is coming from but it has nothing to do with GravityBox.
`com.android.systemui.statusbar.policy.NetworkTrafficSB cannot be cast to com.android.systemui.statusbar.StatusBarIconView`


Full stack trace of crash:
`FATAL EXCEPTION: main
Process: com.android.systemui, PID: 5349
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.RINGER_MODE_CHANGED flg=0x34000010 (has extras) } in com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6@50b1028
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassCastException: com.android.systemui.statusbar.policy.NetworkTrafficSB cannot be cast to com.android.systemui.statusbar.StatusBarIconView
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIcon(StatusBarIconController.java:363)
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIconHolder(StatusBarIconController.java:370)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.lambda$handleSet$4(StatusBarIconControllerImpl.java:307)
	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBarIconControllerImpl$ayp5xWywAkBOOSd-6MshVHM8Mms.accept(Unknown Source:6)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.handleSet(StatusBarIconControllerImpl.java:307)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setIcon(StatusBarIconControllerImpl.java:165)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateAlarm(PhoneStatusBarPolicy.java:288)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateVolumeZen(PhoneStatusBarPolicy.java:390)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.access$900(PhoneStatusBarPolicy.java:83)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6.onReceive(PhoneStatusBarPolicy.java:734)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
	... 8 more`

**Comment by usamaiqbal1177** [comment]
> It's crashing due to some mysterious "NetworkTrafficSB" element in system icon area.
> I don't know where this element is coming from but it has nothing to do with GravityBox.
> `com.android.systemui.statusbar.policy.NetworkTrafficSB cannot be cast to com.android.systemui.statusbar.StatusBarIconView`
> 
> Full stack trace of crash:
> `FATAL EXCEPTION: main Process: com.android.systemui, PID: 5349 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.RINGER_MODE_CHANGED flg=0x34000010 (has extras) } in com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6@50b1028 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560) at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) at android.os.Handler.handleCallback(Handler.java:883) at android.os.Handler.dispatchMessage(Handler.java:100) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) Caused by: java.lang.ClassCastException: com.android.systemui.statusbar.policy.NetworkTrafficSB cannot be cast to com.android.systemui.statusbar.StatusBarIconView at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIcon(StatusBarIconController.java:363) at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIconHolder(StatusBarIconController.java:370) at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.lambda$handleSet$4(StatusBarIconControllerImpl.java:307) at com.android.systemui.statusbar.phone.-$$Lambda$StatusBarIconControllerImpl$ayp5xWywAkBOOSd-6MshVHM8Mms.accept(Unknown Source:6) at java.util.ArrayList.forEach(ArrayList.java:1262) at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.handleSet(StatusBarIconControllerImpl.java:307) at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setIcon(StatusBarIconControllerImpl.java:165) at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateAlarm(PhoneStatusBarPolicy.java:288) at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateVolumeZen(PhoneStatusBarPolicy.java:390) at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.access$900(PhoneStatusBarPolicy.java:83) at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6.onReceive(PhoneStatusBarPolicy.java:734) at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550) ... 8 more`

Thanks for looking into the issue. I'll try to change Network Traffic indicator provided by arrow OS. And see if the issue persist

**Comment by usamaiqbal1177** [comment]
From what I have seen is that GravityBox doesn't work on roms like Arrow OS, AEX. Hope you'll fix that on these roms also.

**Comment by usamaiqbal1177** [comment]
@C3C0 this issue with network traffic element is still there with newer traffic meter. But i installed ancient OS and it had the old traffic meter, but this issue still occurring... Can u plz fix it in the next update, sir? This is the only major issue for me which doesn't let gb run

**Comment by usamaiqbal1177** [comment]
@C3C0 broh, the issue still persist even with 10.0.1 update of gb.. Those roms that have newer style traffic meter (as shown in the picture) the gravity box gives black screen on lockscreen right after reboot. Making you unable to enter the phone. The logs already given in above post. Can you look into that please? 
![IMG_20201110_231154_008_1](https://user-images.githubusercontent.com/58624914/98714160-5dcc1380-23aa-11eb-83cb-4acec78f00d8.jpg)
