### ISSUE TITLE
New style traffic meter in roms not supported. Resubmit #2047

### ISSUE THREAD

**Issue by usamaiqbal1177** [GravityBox/GravityBox#2086]
The issue was also mentioned in January #2047 
@C3C0 broh, the issue still persist even with 10.0.1 update of gb.. Those roms that have newer style traffic meter (as shown in the picture) the gravity box gives black screen on lockscreen right after reboot. Making you unable to enter the phone.. Can you look into that please as majority of roms have this new style traffic meter. 
[boot-1970-03-30-01-28-04.log](https://github.com/GravityBox/GravityBox/files/5537793/boot-1970-03-30-01-28-04.log) 
![IMG_20201113_204059_275_1](https://user-images.githubusercontent.com/58624914/99090610-ab39c200-25f0-11eb-94e0-34f1590a48d6.jpg)

**Comment by C3C0** [comment]
There is no GravityBox directly involved in SystemUI crash. There is something wrong with that traffic meter that ROM comes with. It should implement StatusBarIconView interface but it isn't and developers of ROM should take care of it.
Yes, it is possible that GB can indirectly trigger a code path execution which usually dose not get triggered but GB cannot be responsible when there are parts of code in the ROM that don't have marginal cases handled correctly.

`--------- beginning of crash
[ 01-04 12:58:00.083  4191: 4191 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.systemui, PID: 4191
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.RINGER_MODE_CHANGED flg=0x34000010 (has extras) } in com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6@bca5c6c
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassCastException: com.android.systemui.statusbar.policy.NetworkTrafficSB cannot be cast to com.android.systemui.statusbar.StatusBarIconView
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIcon(StatusBarIconController.java:363)
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.onSetIconHolder(StatusBarIconController.java:370)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.lambda$handleSet$4(StatusBarIconControllerImpl.java:307)
	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBarIconControllerImpl$ayp5xWywAkBOOSd-6MshVHM8Mms.accept(Unknown Source:6)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.handleSet(StatusBarIconControllerImpl.java:307)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setIcon(StatusBarIconControllerImpl.java:165)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateAlarm(PhoneStatusBarPolicy.java:288)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.updateVolumeZen(PhoneStatusBarPolicy.java:390)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy.access$900(PhoneStatusBarPolicy.java:83)
	at com.android.systemui.statusbar.phone.PhoneStatusBarPolicy$6.onReceive(PhoneStatusBarPolicy.java:734)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
	... 8 more`

**Comment by C3C0** [comment]
I just checked Arrow OS github and noticed they already fixed that here:
https://github.com/ArrowOS/android_frameworks_base/commit/2998adadd55aa4e2312bf00ba787c8abf0d55d74#diff-b14675eefdd6ab1080b70407a0ca606d466b8a4075f226165d20e90f8f153df3

So as long as you run fixed version or other ROM that has also that fix, you dhoule be fine.

**Comment by usamaiqbal1177** [comment]
> I just checked Arrow OS github and noticed they already fixed that here:
> [ArrowOS/android_frameworks_base@2998ada#diff-b14675eefdd6ab1080b70407a0ca606d466b8a4075f226165d20e90f8f153df3](https://github.com/ArrowOS/android_frameworks_base/commit/2998adadd55aa4e2312bf00ba787c8abf0d55d74#diff-b14675eefdd6ab1080b70407a0ca606d466b8a4075f226165d20e90f8f153df3)
> 
> So as long as you run fixed version or other ROM that has also that fix, you dhoule be fine.

Oh, okay. I'm trying the latest arrow 10 now. Will report if this finally works

**Comment by usamaiqbal1177** [comment]
@C3C0 I just installed arrow and with the new fix in arrow roms, it is fixed and gb is working so fine now!! ☺️ I hope other roms implement this as well. Thanks a lot!!
